urls.py
# Copyright 2008 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Top-level URL mappings for Rietveld."""

# NOTE: Must import *, since Django looks for things here, e.g. handler500.
from django.conf.urls.defaults import *

urlpatterns = patterns(
    '',
    url(r'', include('codereview.urls')),
    )

codereview/models.py
# Copyright 2008 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""App Engine data model (schema) definition for Rietveld."""

# Python imports
import logging
import re

# AppEngine imports
from google.appengine.ext import db
from google.appengine.api import memcache

# Local imports
import engine
import patching


CONTEXT_CHOICES = (3, 10, 25, 50, 75, 100)


### GQL query cache ###


_query_cache = {}


def gql(cls, clause, *args, **kwds):
  """Return a query object, from the cache if possible.

  Args:
    cls: a db.Model subclass.
    clause: a query clause, e.g. 'WHERE draft = TRUE'.
    *args, **kwds: positional and keyword arguments to be bound to the query.

  Returns:
    A db.GqlQuery instance corresponding to the query with *args and
    **kwds bound to the query.
  """
  query_string = 'SELECT * FROM %s %s' % (cls.kind(), clause)
  query = _query_cache.get(query_string)
  if query is None:
    _query_cache[query_string] = query = db.GqlQuery(query_string)
  query.bind(*args, **kwds)
  return query


### Issues, PatchSets, Patches, Contents, Comments, Messages ###


class Issue(db.Model):
  """The major top-level entity.

  It has one or more PatchSets as its descendants.
  """

  subject = db.StringProperty(required=True)
  description = db.TextProperty()
  base = db.StringProperty()
  local_base = db.BooleanProperty(default=False)
  owner = db.UserProperty(auto_current_user_add=True, required=True)
  created = db.DateTimeProperty(auto_now_add=True)
  modified = db.DateTimeProperty(auto_now=True)
  reviewers = db.ListProperty(db.Email)
  cc = db.ListProperty(db.Email)
  closed = db.BooleanProperty(default=False)
  n_comments = db.IntegerProperty()

  _is_starred = None

  @property
  def is_starred(self):
    """Whether the current user has this issue starred."""
    if self._is_starred is not None:
      return self._is_starred
    account = Account.current_user_account
    self._is_starred = account is not None and self.key().id() in account.stars
    return self._is_starred

  def user_can_edit(self, user):
    """Return true if the given user has permission to edit this issue."""
    return user == self.owner

  @property
  def edit_allowed(self):
    """Whether the current user can edit this issue."""
    return self.user_can_edit(Account.current_user_account.user)

  def update_comment_count(self, n):
    """Increment the n_comments property by n.

    If n_comments in None, compute the count through a query.  (This
    is a transitional strategy while the database contains Issues
    created using a previous version of the schema.)
    """
    if self.n_comments is None:
      self.n_comments = self._get_num_comments()
    self.n_comments += n

  @property
  def num_comments(self):
    """The number of non-draft comments for this issue.

    This is almost an alias for self.n_comments, except that if
    n_comments is None, it is computed through a query, and stored,
    using n_comments as a cache.
    """
    if self.n_comments is None:
      self.n_comments = self._get_num_comments()
    return self.n_comments

  def _get_num_comments(self):
    """Helper to compute the number of comments through a query."""
    return gql(Comment,
               'WHERE ANCESTOR IS :1 AND draft = FALSE',
               self).count()

  _num_drafts = None

  @property
  def num_drafts(self):
    """The number of draft comments on this issue for the current user.

    The value is expensive to compute, so it is cached.
    """
    if self._num_drafts is None:
      account = Account.current_user_account
      if account is None:
        self._num_drafts = 0
      else:
        query = gql(Comment,
            'WHERE ANCESTOR IS :1 AND author = :2 AND draft = TRUE',
            self, account.user)
        self._num_drafts = query.count()
    return self._num_drafts


class PatchSet(db.Model):
  """A set of patchset uploaded together.

  This is a descendant of an Issue and has Patches as descendants.
  """

  issue = db.ReferenceProperty(Issue)  # == parent
  message = db.StringProperty()
  data = db.BlobProperty()
  url = db.LinkProperty()
  owner = db.UserProperty(auto_current_user_add=True, required=True)
  created = db.DateTimeProperty(auto_now_add=True)
  modified = db.DateTimeProperty(auto_now=True)
  n_comments = db.IntegerProperty()
  
  def update_comment_count(self, n):
    """Increment the n_comments property by n.

    If n_comments in None, compute the count through a query.  (This
    is a transitional strategy while the database contains Issues
    created using a previous version of the schema.)
    """
    self.n_comments = self._get_num_comments() + n

  @property
  def num_comments(self):
    """The number of non-draft comments for this issue.

    This is almost an alias for self.n_comments, except that if
    n_comments is None, it is computed through a query, and stored,
    using n_comments as a cache.
    """
    if self.n_comments is None:
      self.n_comments = self._get_num_comments()
    return self.n_comments

  def _get_num_comments(self):
    """Helper to compute the number of comments through a query."""
    return gql(Comment,
               'WHERE ANCESTOR IS :1 AND draft = FALSE',
               self).count()


class Message(db.Model):
  """A copy of a message sent out in email.

  This is a descendant of an Issue.
  """

  issue = db.ReferenceProperty(Issue)  # == parent
  subject = db.StringProperty()
  sender = db.EmailProperty()
  recipients = db.ListProperty(db.Email)
  date = db.DateTimeProperty(auto_now_add=True)
  text = db.TextProperty()
  draft = db.BooleanProperty(default=False)


class Content(db.Model):
  """The content of a text file.

  This is a descendant of a Patch.
  """

  # parent => Patch
  text = db.TextProperty()
  data = db.BlobProperty()
  # Checksum over text or data depending on the type of this content.
  checksum = db.TextProperty()
  is_uploaded = db.BooleanProperty(default=False)
  is_bad = db.BooleanProperty(default=False)
  file_too_large = db.BooleanProperty(default=False)

  @property
  def lines(self):
    """The text split into lines, retaining line endings."""
    if not self.text:
      return []
    return self.text.splitlines(True)


class Patch(db.Model):
  """A single patch, i.e. a set of changes to a single file.

  This is a descendant of a PatchSet.
  """

  patchset = db.ReferenceProperty(PatchSet)  # == parent
  filename = db.StringProperty()
  status = db.StringProperty()  # 'A', 'A  +', 'M', 'D' etc
  text = db.TextProperty()
  content = db.ReferenceProperty(Content)
  patched_content = db.ReferenceProperty(Content, collection_name='patch2_set')
  is_binary = db.BooleanProperty(default=False)
  # Ids of patchsets that have a different version of this file.
  delta = db.ListProperty(int)
  delta_calculated = db.BooleanProperty(default=False)

  _lines = None

  @property
  def lines(self):
    """The patch split into lines, retaining line endings.

    The value is cached.
    """
    if self._lines is not None:
      return self._lines
    if not self.text:
      lines = []
    else:
      lines = self.text.splitlines(True)
    self._lines = lines
    return lines

  _property_changes = None

  @property
  def property_changes(self):
    """The property changes split into lines.

    The value is cached.
    """
    if self._property_changes != None:
      return self._property_changes
    self._property_changes = []
    match = re.search('^Property changes on.*\n'+'_'*67+'$', self.text,
                      re.MULTILINE)
    if match:
      self._property_changes = self.text[match.end():].splitlines()
    return self._property_changes

  _num_lines = None

  @property
  def num_lines(self):
    """The number of lines in this patch.

    The value is cached.
    """
    if self._num_lines is None:
      self._num_lines = len(self.lines)
    return self._num_lines

  _num_chunks = None

  @property
  def num_chunks(self):
    """The number of 'chunks' in this patch.

    A chunk is a block of lines starting with '@@'.

    The value is cached.
    """
    if self._num_chunks is None:
      num = 0
      for line in self.lines:
        if line.startswith('@@'):
          num += 1
      self._num_chunks = num
    return self._num_chunks

  _num_comments = None

  @property
  def num_comments(self):
    """The number of non-draft comments for this patch.

    The value is cached.
    """
    if self._num_comments is None:
      self._num_comments = gql(Comment,
                               'WHERE patch = :1 AND draft = FALSE',
                               self).count()
    return self._num_comments

  _num_drafts = None

  @property
  def num_drafts(self):
    """The number of draft comments on this patch for the current user.

    The value is expensive to compute, so it is cached.
    """
    if self._num_drafts is None:
      account = Account.current_user_account
      if account is None:
        self._num_drafts = 0
      else:
        query = gql(Comment,
                    'WHERE patch = :1 AND draft = TRUE AND author = :2',
                    self, account.user)
        self._num_drafts = query.count()
    return self._num_drafts

  def get_content(self):
    """Get self.content, or fetch it if necessary.

    This is the content of the file to which this patch is relative.

    Returns:
      a Content instance.

    Raises:
      engine.FetchError: If there was a problem fetching it.
    """
    try:

templates/all.html
{%extends "issue_base.html"%}
{%block title1%}Recent Issues -{%endblock%}
{%block body%}
<script language="JavaScript" type="text/javascript"><!--
function keyPressIntermediary(evt) {
  return M_dashboardKeyPress(evt);
}
document.onkeypress = keyPressIntermediary;
-->
</script>
<h2>Recent Issues</h2>

<div class="issue-list">
  <div class="pagination">
    {%if newest%}
      <a class="novisit" href="{{newest}}">&laquo; Newest</a>
    {%endif%}
    {%if prev%}
      <a class="novisit" href="{{prev}}">&lsaquo; Newer</a>
    {%endif%}
    <b>{{first}}{%if last%} - {{last}}{%endif%}</b>
    {%if next%}<a class="novisit" href="{{next}}">Older &rsaquo;</a>
    {%else%}<span style="color:gray">Older &rsaquo;</span>{%endif%}
  </div>

  <table id="queues">
    {%if not issues%}
      <tr><td colspan="9"><span class="disabled">(None)</span></td></tr>
    {%else%}
      {%include "issue_heading.html"%}
      {%for issue in issues%}
        {%include "issue_row.html"%}
      {%endfor%}
    {%endif%}
  </table>

  <div class="pagination">
    {%if newest%}
      <a class="novisit" href="{{newest}}">&laquo; Newest</a>
    {%endif%}
    {%if prev%}
      <a class="novisit" href="{{prev}}">&lsaquo; Newer</a>
    {%endif%}
    <b>{{first}}{%if last%} - {{last}}{%endif%}</b>
    {%if next%}<a class="novisit" href="{{next}}">Older &rsaquo;</a>
    {%else%}<span style="color:gray">Older &rsaquo;</span>{%endif%}
  </div>

</div>

<script language="JavaScript" type="text/javascript"><!--
var dashboardState = new M_DashboardState(window,'issue');
-->
</script>
{%endblock%}

templates/inline_comment.html
{%for c in comments%}
<div class="comment-border{%if c.confidence%} conf{{c.confidence}}{%endif%} {{c.backend}}" name="comment-border">
<div class="inline-comment-title" onclick="M_switchInlineComment({{forloop.counter0}}, {{lineno}}, '{{side}}')">
{%if c.draft%}<b>(Draft)</b>{%else%}<b>{{c.author|nickname}}</b>{%endif%}
{%if c.confidence_text%} <b>(confidence {{c.confidence_text}})</b>{%endif%}
{{c.date|date:"Y/m/d H:i:s"}}
<span id="inline-preview-{{forloop.counter0}}-{{lineno}}-{{side}}" 
  class="extra" name="inline-preview"
  {%if c.draft%}style="visibility: hidden"{%endif%}>{{c.shorttext}}</span>
</div>
<div id="inline-comment-{{forloop.counter0}}-{{lineno}}-{{side}}"
     class="inline-comment"
     name="inline-comment"
     {%if c.draft%}ondblclick="M_editInlineComment({{forloop.counter0}}, {{lineno}}, '{{side}}'); M_stopBubble(window, event);"{%endif%}
     {%if not c.draft%}style="display: none"{%endif%}>
{%for bucket in c.buckets%}
{%if bucket.quoted%}
<div><a class="comment-hide-link" href="javascript:M_switchQuotedText({{forloop.parentloop.counter0}}, {{forloop.counter0}}, {{lineno}}, '{{side}}')">(Un)hide quoted text</a></div>
{%endif%}
<div name="comment-text-{{forloop.parentloop.counter0}}-{{lineno}}-{{side}}"
id="comment-text-{{forloop.parentloop.counter0}}-{{lineno}}-{{side}}-{{forloop.counter0}}"
class="{%if bucket.quoted%}comment-text-quoted{%else%}comment-text{%endif%}"
{%if bucket.quoted%}style="display: none"{%endif%}
>{{bucket.text|wordwrap:"80"|escape|urlize}}</div>
{%endfor%}
{%if c.draft%}
<a name="comment-reply"
   id="edit-link-{{forloop.counter0}}-{{lineno}}-{{side}}"
   href="javascript:M_editInlineComment({{forloop.counter0}}, {{lineno}}, '{{side}}')"><b>Edit</b></a>
<a name="comment-reply"
   id="undo-link-{{forloop.counter0}}-{{lineno}}-{{side}}"
   style="display:none"
   href="javascript:M_restoreEditInlineComment({{forloop.counter0}}, {{lineno}}, '{{side}}')"><b>Undo cancel</b></a>
<form id="comment-form-{{forloop.counter0}}-{{lineno}}-{{side}}"
      name="comment-form-{{forloop.counter0}}-{{lineno}}-{{side}}"
      style="display:none" action="{%url codereview.views.inline_draft%}" method = "POST">
<div name="form-container">
<input type="hidden" name="issue" value="{{issue.key.id}}">
<input type="hidden" name="patchset" value="{{patchset.key.id}}">
<input type="hidden" name="patch" value="{{patch.key.id}}">
<input type="hidden" name="snapshot" value="{{snapshot}}">
<input type="hidden" name="side" value="{{side}}">
<input type="hidden" name="file" value="{{file.depot_path|escape}}">
<input type="hidden" name="lineno" value="{{lineno}}">
<input type="hidden" name="oldtext" value="{{c.text}}">
{%if c.message_id%}<input type="hidden" name="message_id" value="{{c.message_id}}">{%endif%}
<textarea name="text" cols="60" rows="5">{{c.text}}</textarea><br>
<input type="submit" name="save" value="Save" onclick="return M_submitInlineComment(this.form, {{forloop.counter0}}, {{lineno}}, '{{side}}')">
<input type="reset" name="cancel" value="Cancel" onclick="M_resetAndHideInlineComment(this.form, {{forloop.counter0}}, {{lineno}}, '{{side}}')">
<input type="submit" name="discard" value="Discard" onclick="return M_removeInlineComment(this.form, {{forloop.counter0}}, {{lineno}}, '{{side}}')">
</div>
</form>
{%else%}
{%if user%}
<a name="comment-reply"
   href="javascript:M_replyToInlineComment('{{c.author|nickname:"x"}}', '{{c.date|date:"Y/m/d H:i:s"}}', {{forloop.counter0}}, {{lineno}}, '{{side}}')"
><b>Reply</b></a>
{%if c.backend%}<a href="javascript:M_replyToInlineComment('{{c.author|nickname:"x"}}', '{{c.date|date:"Y/m/d H:i:s"}}', {{forloop.counter0}}, {{lineno}}, '{{side}}', 'Please fix.', true)"><b>Please fix</b></a>
{%else%}<a href="javascript:M_replyToInlineComment('{{c.author|nickname:"x"}}', '{{c.date|date:"Y/m/d H:i:s"}}', {{forloop.counter0}}, {{lineno}}, '{{side}}', 'Done.', true)"><b>Done</b></a>{%endif%}
{%ifequal c.backend "bugbot"%} &nbsp; <a target="_blank" href="http://bugbotexp{{file.depot_path|escape}}"><b>&raquo; Suppress</b></a>{%endifequal%}
{%endif%}
{%endif%}
</div>
</div>
{%endfor%}
<div class="comment-border" style="padding: 0"></div>

templates/issue_row.html
<tr {%if issue.num_drafts%}style="color:red"{%endif%} name="issue">
  <td class="first" width="14"><img src="/static/closedtriangle.gif" 
    style="visibility: hidden;" width="12" height="9" /></td>
  <td width="17" align="center">{%include "issue_star.html"%}</td>
  <td align="right"><div class="subject"><a class="noul"
         href="{%url codereview.views.show issue.key.id%}">{{issue.key.id}}</a>
     </div>
  </td>
  <td>
    <div class="subject">
      <a class="noul" href="{%url codereview.views.show issue.key.id%}">
        {{issue.subject}}</a>
      {%if issue.closed and not closed_issues %} (Closed) {%endif%}
    </div>
  </td>
  <td><div class="users">{{issue.owner|show_user}}</div></td>
  <td><div class="users">{{issue.reviewers|show_users}}</div></td>
  <td align="center">{%firstof issue.num_comments%}</td>
  <td align="center"><b>{%firstof issue.num_drafts%}</b></td>
  <td class="last"><div class="date">{{issue.modified|timesince}}</div></td>
</tr>

templates/issue_star.html
<span id="issue-star-{{issue.key.id}}">
  {%if issue.is_starred%}
    <a href="javascript:M_removeIssueStar({{issue.key.id}})">
      <img src="/static/star-lite.gif" width="15" height="15" border="0"></a>
  {%else%}
    {%if request.user%}
      <a href="javascript:M_addIssueStar({{issue.key.id}})">
	<img src="/static/star-dark.gif" width="15" height="15" border="0"></a>
    {%endif%}
  {%endif%}
</span>

templates/new.html
{%extends "issue_base.html"%}
{%block title1%}Create Issue -{%endblock%}
{%block body%}

{%if form.errors%}
<h2>There Were Errors!</h2>
{%else%}
<h2>Create New Issue</h2>
{%endif%}

<p>Download <a href="/static/upload.py">upload.py</a>, a simple tool for
uploading diffs from a version control system to the codereview app.</p>

<form action="{%url codereview.views.new%}"
      method="post" enctype="multipart/form-data" id="create-form">
<table>
{{form}}
<tr><td><input type="submit" value="Create Issue"></td></tr>
</table>
</form>

<a id="resizer" style="display:none;cursor:pointer">
<img src="/static/zippyplus.gif"></a>
<script language="JavaScript" type="text/javascript"><!--
M_addTextResizer_(document.getElementById("create-form"));
--></script>

{%endblock%}

templates/patch.html
{%extends "issue_base.html"%}
{%block body%}

<script language="JavaScript" type="text/javascript"><!--
function keyPressIntermediary(evt) {
  return M_keyPress(evt);
}
document.onkeypress = keyPressIntermediary;
{%if user%}
logged_in = true;
{%else%}
logged_in = false;
login_warned = false;
{%endif%}
// -->
</script>

{%if user%}
<!-- Form used by in-line comment JS; XXX filled in by JS code -->
<form id="dainlineform" style="display: none;"
      action="{%url codereview.views.inline_draft%}" method="post">
  <div class="comment-border" name="form-container">
    <input type="hidden" name="snapshot" value="XXX">
    <input type="hidden" name="lineno" value="XXX">
    <input type="hidden" name="side" value="XXX">
    <input type="hidden" name="issue" value="{{issue.key.id}}">
    <input type="hidden" name="patchset" value="{{patchset.key.id}}">
    <input type="hidden" name="patch" value="{{patch.key.id}}">
    <textarea name="text" cols="60" rows="5"></textarea><br>
    <input type="submit" name="save" value="Save"
           onclick="return M_submitInlineComment(this.form);">
    <input type="reset" name="cancel" value="Cancel"
           onclick="M_removeTempInlineComment(this.form)">
  </div>
  <div class="comment-border" style="padding: 0pt;"></div>
</form>
<a id="resizer" style="display:none;cursor:pointer"><img src="/static/zippyplus.gif"></a>
{%endif%}

<div style="float: left;">
  <h2 style="margin-bottom: 0em; margin-top: 0em;">Unified Diff: {{patch.filename}}</h2>
  {%ifnotequal patch.nav_type "patch"%}
    <span style="color:red">Side-by-side diff isn't available for this file because of its large size.</span>
  {%endifnotequal%}
  <div style="margin-top: .2em;">{%include "issue_star.html"%}
    <b>Issue <a href="{%url codereview.views.show issue.key.id%}" onmouseover="M_showPopUp(this, 'popup-issue');" id="upCL">{{issue.key.id}}</a>:</b>
  {{issue.subject}} {%if issue.closed %} (Closed) {%endif%}
  {%if issue.base%}<span class="extra">SVN Base: {{issue.base}}</span>{%endif%}</div>
  <div style="margin-top: .4em;">
    <b>Patch Set: {%if patchset.message%}{{patchset.message}}{%endif%}</b>
    <span class="extra">
    Created {{patchset.created|timesince}} ago
    {%ifnotequal patchset.owner issue.owner%}
    by <b>{{patchset.owner|show_user}}</b>{%endifnotequal%}
    {%if patchset.url%},
    Downloaded from: <a href="{{patchset.url}}">{{patchset.url}}</a>
    {%endif%}
    </span>
  </div>
  <div style="margin-top: .4em;" class="help">
    Use n/p to move between diff chunks;
    N/P to move between comments.
    {%if user%}
    Double-click a line to add a draft in-line comment.
    <br><span style="color:red">Draft comments are only viewable by you;</span>
    use <a href="{%url codereview.views.publish issue.key.id%}" class="novisit">Publish+Mail Comments</a> ('m') to let others view them.
    {%else%}
    Please Sign in to add in-line comments.
    {%endif%}
  </div>
</div>
{%if column_width and context%}
  <input type="hidden" id="id_context" value="{{context}}" />
  <input type="hidden" id="id_column_width" value="{{column_width}}" />
{%endif%}
<div style="float: right; color: #333333; background-color: #eeeeec; border: 1px solid lightgray; -moz-border-radius: 5px 5px 5px 5px; padding: 5px;">
  <div>
    Jump to: <select onchange="M_jumpToPatch(this, {{issue.key.id}}, {{patchset.key.id}}, true);">
      {% for jump_patch in patchset.patch_set %}
        <option value="{{jump_patch.key.id}}"
         {%ifequal jump_patch.key.id patch.key.id%} selected="selected"{%endifequal%}>{{jump_patch.filename}}</option>
      {% endfor %}
    </select>
  </div>
  {%if not patch.no_base_file%}
  <div style="margin-top: 5px;">
    <a href="{%url codereview.views.diff issue.key.id,patchset.key.id,patch.key.id%}{%urlappend_view_settings%}">
    View side by-side-diff with in-line comments</a>
  </div>
  {%endif%}
  <div style="margin-top: 5px;">
    <a href="{%url codereview.views.download_patch issue.key.id,patchset.key.id,patch.key.id%}"
       title="Download patch for {{patch.filename}}">
      Download patch
    </a>
  </div>
  {%if user%}
  <div style="margin-top: 5px;">
    <a class="novisit" href="{%url codereview.views.publish issue.key.id%}">Publish+Mail
    Comments</a> ('m')
    |
    <a class="novisit" href="javascript:draftMessage.dialog_show()">Edit draft message</a> ('M')
  </div>
  {%endif%}
</div>
<div style="clear: both;"></div>

<div class="code" style="margin-top: 1.3em; display: table; margin-left: auto; margin-right: auto;">

<div class="codenav">
{%if patch.prev%}
<a id="prevFile"
   href="{%url codereview.views.patch issue.key.id,patchset.key.id,patch.prev.key.id%}{%urlappend_view_settings%}">
&laquo; {{patch.prev.filename}}</a> ('k'){%else%}
<span class="disabled">&laquo; no previous file</span>{%endif%}
|
{%if patch.next%}
<a id="nextFile"
   href="{%url codereview.views.patch issue.key.id,patchset.key.id,patch.next.key.id%}{%urlappend_view_settings%}">
{{patch.next.filename}} &raquo;</a> ('j'){%else%}
<span class="disabled">no next file &raquo;</span>{%endif%}
|
<a href="javascript:M_expandAllInlineComments()">Expand Comments</a> ('e')
|
<a href="javascript:M_collapseAllInlineComments()">Collapse Comments</a> ('c')
|
<a name="show-all-inline"
   style="display:none"
   href="javascript:M_showAllInlineComments()">Show Comments</a>
<a name="hide-all-inline"
   href="javascript:M_hideAllInlineComments()">Hide Comments</a> ('s')
</div>

<div style="position:relative" id="table-top">

{%if patch.is_binary%}
<img src="{%url codereview.views.image issue.key.id,patchset.key.id,patch.key.id,1%}" />
</pre>
{%else%}
<span id="hook-sel" style="display:none;"></span>

<table style="padding: 5px;" cellpadding="0" cellspacing="0" id="thecode"
       ondblclick="M_handleTableDblClick(event)">
{%for row in rows%}{{row|safe}}{%endfor%}
</table>
{%endif%}

</div>
<div class="codenav">
{%if patch.prev%}
<a id="prevFile"
   href="{%url codereview.views.patch issue.key.id,patchset.key.id,patch.prev.key.id%}{%urlappend_view_settings%}">
&laquo; {{patch.prev.filename}}</a> ('k'){%else%}
<span class="disabled">&laquo; no previous file</span>{%endif%}
|
{%if patch.next%}
<a id="nextFile"
   href="{%url codereview.views.patch issue.key.id,patchset.key.id,patch.next.key.id%}{%urlappend_view_settings%}">
{{patch.next.filename}} &raquo;</a> ('j'){%else%}
<span class="disabled">no next file &raquo;</span>{%endif%}
</div>
</div>

</script>
<script language="JavaScript" type="text/javascript"><!--
var old_snapshot = "old";
var new_snapshot = "new";
var intraLineDiff = new M_IntraLineDiff();
var hookState = new M_HookState(window);
hookState.updateHooks();


// -->
</script>

{%include "draft_message.html"%}

{%endblock%}

templates/repos.html
{%extends "repos_base.html"%}
{%block title1%}Repositories -{%endblock%}
{%block body%}
<h2>Repositories and Branches</h2>

{%for br in branches%}
{%ifchanged%}<h3>Repository: {{br.repo.name}}</h3>
{%if user%}
<p>(<a href="{%url codereview.views.branch_new br.repo.key.id%}">add branch</a>)
{%endif%}
{%endifchanged%}</p>
{{br.category}} {{br.name}} {{br.url}}
{%ifequal br.owner user%}
&nbsp; (<a href="{%url codereview.views.branch_edit br.key.id%}">edit</a>)
{%endifequal%}
<br>
{%endfor%}

{%endblock%}

templates/user_popup.html
<b>{{user.email}} ({{user.nickname}})</b>
<p>
issues created: {{num_issues_created}} <br/>
issues reviewed: {{num_issues_reviewed}}
</p>